### ISSUE TITLE
Window Coverings minstep

### ISSUE THREAD

**Issue by XattSPT** [swttt/com.swttt.homekit#172]
Hi @swttt, 

  on /lib/devices/stateblinds.js line 69, min step should be 1 in order to allow to select any % position. Could you update on future releases? I've tested on local, but I'm not so familiar with branches on Github. 
  
  This will be helpful for Homekit integration with Homey Soma App I've developed.

Thanks in advance.  

Gerard.

**Comment by robertklep** [comment]
The reason it's 50 is because "state blinds" only have three states: up, down and idle.

These need to be mapped to percentages, because that's what HomeKit needs. So "up" is mapped to 100%, down is mapped to 0% and idle is mapped to 50%.

If your app supports a full range of 0 to 100%, you should look at `lib/devices/dimblinds.js`, which uses the "dim" capability to set the cover percentage, or look at `lib/devices/curtains.js`, which uses the "windowcoverings_set" capability.

**Comment by XattSPT** [comment]
Ok thanks for your promt answer.

One question, I do not know how to point to these (dimblinds or curtains) when an accesory is pushed by Homeykit to homekit? Any suggestion? Do I need to change any definition on my app? I havent found any option on Homeykit.

Thanks in advance,

G.

**Comment by robertklep** [comment]
HomeyKit tries to match Homey device class and capabilities to HomeKit services and characteristics, respectively. An app developer doesn't have much influence over how a device is presented to HomeKit, other than setting the correct device class (`curtain`, `window_covering`, ...) and using capabilities that HomeyKit knows how to handle.

So for your app, which device class are you using for the devices, and which capabilities do they support?

**Comment by XattSPT** [comment]
Windowcoverings_set and windowcovering_state 

According to your post it should detect as curtains, but I cant see curtains.js on repo. Do I installing correct version?

Many thanks for your help.

Other option should be to change windowcoverings_set by dim...

**Comment by XattSPT** [comment]
I found the problem.

I should add 'curtain' capability to be correctly detected on beta version (that allows curtains)

Many thanks for your replies.
