### ISSUE TITLE
Thermostat 0.5 degree increments

### ISSUE THREAD

**Issue by mchlrv** [swttt/com.swttt.homekit#183]
It is not possible to set the temperature in increments of 0.5 degree within the Apple Home application. When controlling the thermostat from the Homey app it is possible and the Apple Home application reflects the .5 temperature.

**Comment by robertklep** [comment]
That seems to be an issue with the iOS Home app, the same happens for me. With other Homekit apps (like Eve) I can set half degrees just fine.

**Comment by mchlrv** [comment]
But if the issues doesn't happen with other Homekit apps, then I would assume that the issue is with Homeykit, right?

- So in your example, Eve exports thermostat to iOS Home and you can set half degrees.
- Homeykit exports thermostat to iOS Home and you can not set half degrees.

**Comment by robertklep** [comment]
> But if the issues doesn't happen with other Homekit apps, then I would assume that the issue is with Homeykit, right?

No, it means the issue is with Apple's Home app, which apparently refuses to set half-degrees.

I've tested the [Eve app](https://apps.apple.com/us/app/eve-for-homekit/id917695792) and [Home+ 4](https://apps.apple.com/us/app/home-smart-home-automation/id995994352) as alternatives for Apple's Home app, and both are perfectly fine with setting half-degrees (Home+ even accepts tens-of-degrees).

All apps use Homeykit directly, so it works like this:
* Homeykit exports thermostat to iOS Home and you can not set half degrees.
* Homeykit exports thermostat to Eve and you can set half degrees.
* Homeykit exports thermostat to Home+ and you can set tens-of-degrees.
