### ISSUE TITLE
Not compatible with Homey Bridge

### ISSUE THREAD

**Issue by Ounihoun** [swttt/com.swttt.homekit#206]
Hello, do you know when Homeykit will be compatible with Homey bridge ? 
Thanks.

**Comment by robertklep** [comment]
Probably never, for many reasons:
* Athom requires developers to pay to get the "privilege" of developing apps for Homey Cloud/Bridge
* Athom only wants "brand-name" apps for Cloud/Bridge
* "tool" type apps will not be accepted for Cloud/Bridge
* the Bridge device doesn't have enough processing power for local networking, which is required for the HomeKit protocol

**Comment by Ounihoun** [comment]
Ah… really too bad… I didn't know that  when I bought Homey Bridge… Thank you for your answer.

**Comment by robertklep** [comment]
The Bridge is a very limited device 😢 Even though Athom tries to sell the Bridge by stating it supports 50.000+ devices, that's complete BS given the small amount of apps available for it.

**Comment by kikiwora** [comment]
Yeah, Bridge is total bullshit. Of all my devices at home, I've been able to connect only one - Zigbee Lamp (Phillips HUE).

I could not connect my air purifier, my fan, my humidifier, my other lamps, cause the Bridge still does not support Xiaomi devices, since the plugin is available only for Homey Pro.

And ofc, this is ultimately useless for me, since even this singular device cannot be added to HomeKit (the only reason I've purchased Homey Bridge, is to add such devices to my Home and avoid purchasing different hubs of different vendors).

Essentially, all of this renders both HomeyKit plugin and HomeyBridge totally useless, since non of those work in the end.

I do not understand what Athom is doing. They've positioned Homey Bridge as cheaper version of Pro device, that runs all hard logic at the Cloud (for which the end-user pays), why they're limiting third-party apps in unclear.
