### ISSUE TITLE
HomeKit devices not responding

### ISSUE THREAD

**Issue by mrkernels** [swttt/com.swttt.homekit#228]
Hi,

After Homey Pro updated to 8.0 and later versions (now 8.0.3) HomeyKit has been flakey. All devices appear as Not Responding and I've reinstalled and "clean and rebuild" and now I cannot add HomeyKit back to Home app (searching forever).

Restarted Homey and uninstalled/reinstalled multiple times.

Is there any way to get logs/console from Homey/HomeyKit to see what's going on?

Not a dev so sorry for dumb questions

**Comment by robertklep** [comment]
Homey doesn't provide any logging, all you can do is run HomeyKit from the commandline to see what's happening with the app, but it probably won't give you a lot of information because these kinds of issues occur deep within Homey's core anyway.

There are plenty of issues with the latest firmware versions according to the community forum, so it's not something I can fix anyway 😢 All you can do is try and see if a [PTP](https://community.homey.app/t/how-to-ptp/17304) fixes your issues.

**Comment by dirkg173** [comment]
I have the same issue. But this week Apple published new firmware for (almost?) all Apple devices. So I can't figure out, if Homeys or Apples firmware update caused this issue.

**Comment by robertklep** [comment]
Homey firmware updates _always_ cause issues 🙄
