### ISSUE TITLE
No device response iOS16.1

### ISSUE THREAD

**Issue by MickeH8** [swttt/com.swttt.homekit#247]
All of the devices from Homey via Homeykit shows as no response.
Everything is working when controlled via Homeys “native” HomeKit integration.

I have tried both the latest official release of Homeykit and the latest test build.

**Comment by robertklep** [comment]
I've never been able to track this issue down as an issue with HomeyKit, it's always caused by something external (either Homey's networking being unstable, a HomeKit hub that's misbehaving, or iOS losing its configuration).

If a "pull the plug" (removing Homey from power for about 10 minutes) doesn't solve the problem, your best bet is to perform a storage reset, which you can do from the settings of the HomeyKit app.

Also, enabling the native HomeKit integration and running HomeyKit together can cause issues too.

**Comment by MickeH8** [comment]
Thanks for your reply.
I have tried pull the plug for 10+ minutes.
Have tried storage reset, and changed bridge identifier. But still no go. Now I can’t even find the Homeykit bridge when I try to add it to HomeKit. The “native” HomeKit bridge is found.

**Comment by robertklep** [comment]
After resetting the storage and changing the identifier, did you restart the HomeyKit app (or restart Homey)?

You can try sending a diagnostics report (if you haven't done so already), but this problem seems to be related specifically to Homey and not so much the app itself. At least there are never any clues that the app is having an issue, or that it's crashing, it's just waiting for iOS to connect to it.

**Comment by MickeH8** [comment]
Hi Robert!

Again thanks for your fast reply!
After about 4 resets and restarts of Homey it started to work again.
I’m also leaning toward it was a Homey issue.
Lately it has started to behave strange.
