### ISSUE TITLE
Same issue homekit stopped working 

### ISSUE THREAD

**Issue by Julusmoen** [swttt/com.swttt.homekit#251]
Homekit stopped working iOS 16.3 use test version 5.0.0 not working.

**Comment by robertklep** [comment]
You have to provide more information if you expect help. What does "not working" mean? Have you rebooted your Homey to see if that solves it?

**Comment by Julusmoen** [comment]
The app is unexpectedly stopped, rebooted no contact in HomeKit💁 and homey sends you a message, I will try to reboot again.

**Comment by robertklep** [comment]
If this is your crash report:
```
Error: Service name is already in use on the network
```

Then you have multiple HomeKit installations running on your network with the same name (which is "Homey" by default). Have you enabled the HomeKit Experiment from the Homey app settings?

**Comment by Julusmoen** [comment]
That’s right two homey  but different names on them, not possible? Yes HomeKit experiment👍

**Comment by robertklep** [comment]
It will work if you change the name that HomeyKit uses on the network, but before you can do that you have to disable the HomeKit experiment first, then change the name in the HomeyKit app settings (to "Homey2" or whatever), and then you can enable the HomeKit experiment again, which has a non-configurable name (although I have no idea why you would want to run that, since it's extremely limited).

Alternatively, stop using HomeyKit and install [HomeKitty](https://homey.app/a/name.klep.homekitty/) instead. HomeyKit will not be maintained anymore.

**Comment by Julusmoen** [comment]
Ok thx for answer! I use it for gps and light. Gps on homey unstable. So homekit app will no longer work in the future? Just close issue👍

**Comment by robertklep** [comment]
**HomeyKit** will keep on working, but it's not being developed anymore, so no new features and only minimal bugfixing. All development efforts have been moved to the new HomeKitty app.
