### ISSUE TITLE
Remote connection isn't working anymore

### ISSUE THREAD

**Issue by jwfchris** [swttt/com.swttt.homekit#85]
Hello,

Since a couple of weeks the remote connection with the Homekit App doesn't work anymore. Only if i'm on the same WIFI network as my Homekit Hub it works. Could you help me with this? It seems like it is caused by the recent IOS update

**Comment by robertklep** [comment]
Remote connections work through a hub (AppleTV or iPad) and isn't something explicitly built into the Homey app. I'm running iOS 11.4.1 on my iPhone and remote connections work fine, so it might have to do with your hub.

**Comment by jwfchris** [comment]
Thanks for your reply but I only have problems with the homey connection.
My hue light are directly connected with homekit and are working properly
remote.

Kind regards

Joost

Op za 28 jul. 2018 om 10:46 schreef Robert Klep <notifications@github.com>

**Comment by robertklep** [comment]
The current `beta` branch contains some (untested) code to clear the persistent storage, basically the same as what's being suggested [here](https://github.com/nfarina/homebridge/issues/1739#issuecomment-449288152) (point 3).

However, from what I know (but I haven't tested this yet, because I don't want to lose my HomeKit setup), removing the persistent storage will also remove any client pairing data, meaning that you have to set up HomeKit on your iOS device again.

**Comment by basdeg** [comment]
> The current `beta` branch contains some (untested) code to clear the persistent storage, basically the same as what's being suggested [here](https://github.com/nfarina/homebridge/issues/1739#issuecomment-449288152) (point 3).
> 
> However, from what I know (but I haven't tested this yet, because I don't want to lose my HomeKit setup), removing the persistent storage will also remove any client pairing data, meaning that you have to set up HomeKit on your iOS device again.

I can verify that clearing the persistent storage is solving this issue. 2 Con's:
You need to setup your (Homey suplied) HomeKit devices again. 
This feature is now in the BETA branch, and that version is not working on the stable Homey version (only >2.0).

**Comment by robertklep** [comment]
Re-pairing iOS with Homey automatically implies that you are creating a new pairing, which means having to set up devices/rooms on iOS again :)

And indeed, it's v2.0-only. I don't run v2.0 myself so can't even test it, but Athom has not provided a proper method of publishing both v1.5 and v2.0 versions of the same app. We made the decision to only publish for v2.0 from now on.

A quick and dirty way to force a reset on v1.5 is to uninstall the app from Homey and reinstall it. That should remove all pairing data too.

**Comment by basdeg** [comment]
For Homey 1.5, uninstalling and installing the HomeyKit App will not solve this issue. The devices (after new pairing) will stay unavailable outside LAN.

**Comment by robertklep** [comment]
I think that as long as you are able to pair (and use) Homeykit from your local network, there isn't much that we can do if it doesn't work from _outside_ your local network.

Homeykit doesn't have any explicit code that is used to handle connections from the outside, so that's all handled through the HomeKit protocol, the hub, and iCloud.

I can definitively say that accessing HomeyKit from outside my local network works, so it's not something that is just not supported:

![image](https://user-images.githubusercontent.com/1190916/50441985-50642800-08fd-11e9-8f20-60a2d4e7716b.png)
