### ISSUE TITLE
Need to restart daily

### ISSUE THREAD

**Issue by dansko82** [swttt/com.swttt.homekit#94]
Using homey official release and app Homeykit. works fine but Daily or bi Daily the Connection to apple homekit stops working. Same for my Iphone and my wifes Iphone.
Restart of Homeykit resolves the issue.

It is really annoying. Seems I´m not the only one and I guess you are working on this. Maybe a workaround would be to enable some action card to restart Homeykit Daily? If possible.

**Comment by robertklep** [comment]
You can use the [Candy app](https://apps.athom.com/app/info.matjaz.candy) to restart apps from flows.

We're not working on this, because there's no specific bug that's causing this. Some people have this issue, other people (like myself) don't. It also happens with the other Homekit app for Homey, so it's not an issue that's strictly limited to this app.

I've had similar issues with various open source Homekit bridges, like Homebridge (which uses the same Homekit implementation as this app) and the other Homekit app, but all those issues disappeared with iOS 12 for me.

I do reboot Homey twice a week, but that's not specifically for Homekit.

**Comment by dansko82** [comment]
Hi,

Oh ok. That makes sense. Thanks for candy info, hopefully a nightly restart will make difference.

Best regards
Daniel
________________________________
Från: Robert Klep <notifications@github.com>
Skickat: den 2 december 2018 19:50:05
Till: swttt/com.swttt.homekit
Kopia: dansko82; Author
Ämne: Re: [swttt/com.swttt.homekit] Need to restart daily (#94)


You can use the Candy app<https://apps.athom.com/app/info.matjaz.candy> to restart apps from flows.

We're not working on this, because there's no specific bug that's causing this. Some people have this issue, other people (like myself) don't. It also happens with the other Homekit app for Homey, so it's not an issue that's strictly limited to this app.

I've had similar issues with various open source Homekit bridges, like Homebridge (which uses the same Homekit implementation as this app) and the other Homekit app, but all those issues disappeared with iOS 12 for me.

I do reboot Homey twice a week, but that's not specifically for Homekit.
