### ISSUE TITLE
Add "clear storage" button to settings page

### ISSUE THREAD

**Issue by robertklep** [swttt/com.swttt.homekit#99]
Clearing the storage typically doesn't do any harm, and can solve issues with Homeykit not being discovered by iOS. By adding a button to clear it, we can offer users that have discovery issues a possible solution.

**Comment by basdeg** [comment]
tested this with commit f9689cb at homey 2.0.0-rc.9, works like a charm for once. 

Steps to reproduce:
1. On your Apple device, check the "Home" app to verify that the homey is connected. 
2. In the Homey Beta App, go to Apps and select "HomeyKit", click "configure app" and select the "settings" tab, click "Clear HomeKit storage and start over" confirm "are you sure!?" with "yes" 
3. Go back to the Apple "Home" app to verify that the Homey is disconnected. 
4. Remove the Homey device from the "Home" app and add it again with the original instructions. 
5. In the Homey Beta App, clear the storage again like you did at step 2. 
6. Back in Apples "Home" app, you will now notice that homey is still be connected. Looks like the "clear storage" function is working only once at this moment.

**Comment by robertklep** [comment]
Have you tried removing the Homey device from HomeKit _before_ clearing the storage?

**Comment by basdeg** [comment]
> Have you tried removing the Homey device from HomeKit _before_ clearing the storage?

Maybe that is doing the thing, but i cannot easily verify that the storage is cleared. With the first clear, the Homey device became unavailable in the "Home" app. That did not happen the second time, so that might indicate a problem, or an unexplained but expected behaviour. (p.s. the first clear storage fixed my problems, i was just walking into this by monkey-testing this feature)
